title: Vagus
baseurl: /
url: http://cn.oculus.im

author:
  name: Stephen
  url: /about.html

description: Vagus- a reborn
keywords:
- 

paginate: 10

auto: false
server: false
source: .
destination: ./_site

future: false
permalink: /:year-:month-:day/:title.html
markdown: rdiscount

disqus:stephen_bernie
  shortname: vagus-abducens

google:
  analytics:
    tracking_id: 
    domain_name: 

