title:            Vagus
description:      A Reborn
url:              http://cn.oculus.im
signoff:          Stephen Ong
facebook_appid:   
google_analytics: UA-17275476-4
theme:            b
paginate:         7
owner:
  name:           '川上'
  avatar:         'https://secure.gravatar.com/avatar/6370e601e126e33795c46ca4901de569?s=420&d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png'
  bio:            'The best way to predict the future is to invent it.'

links: 
  - name:         Home
    url:          /
 # - name:         Categories
 #   url:          /categories
  - name:         About
    url:          /about.html
  - name:         Quotes
    url:          /quote.html
 # - name:         Log
 # url:          http://blog.oculus.im
  - name:         Contact
    url:          mailto:i@oculus.im
  #- name:         RSS
  #  url:          /RSS.xml

pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
