title: Stephen Ong
baseurl: /
url: http://cn.oculus.im

author:
  name: Stephen Ong
  url: /about.html

description: Vagus: a reborn
keywords:
- 

paginate: 5

auto: false
server: false
source: .
destination: ./_site

future: false
permalink: /:year-:month-:day/:title.html
markdown: rdiscount

disqus:
  shortname: 

google:
  analytics:
    tracking_id: 
    domain_name: 

